export type CisspQuestion={id:string;statement:string;options:string[];answer:number;subject:string;topic:string;difficulty:"Fácil"|"Médio"|"Difícil";explanation:string;certification:string;examVersion:string};
type Concept={topic:string;ask:string;correct:string;wrong:[string,string,string];why:string};
type Domain={name:string;concepts:Concept[]};

const contexts=[
  "Uma organização global está revisando seu programa de segurança.",
  "Após uma auditoria, o gerente de segurança precisa recomendar uma ação.",
  "Durante uma reunião executiva, surge uma decisão de segurança prioritária.",
  "Uma empresa em rápida expansão identificou uma lacuna de controle.",
  "Como responsável pelo programa de segurança, você avalia o cenário apresentado.",
];
const domains:Domain[]=[
 {name:"1. Security and Risk Management",concepts:[
  {topic:"Gestão de riscos",ask:"Qual deve ser a PRIMEIRA etapa antes de selecionar controles?",correct:"Identificar e avaliar os riscos no contexto dos objetivos do negócio",wrong:["Comprar a ferramenta líder de mercado","Transferir todos os riscos para uma seguradora","Aplicar imediatamente o controle mais restritivo"],why:"Controles devem responder a riscos compreendidos e alinhados aos objetivos do negócio."},
  {topic:"Governança",ask:"Quem deve aceitar formalmente um risco residual significativo?",correct:"O proprietário do risco com autoridade de negócio",wrong:["O analista que encontrou a vulnerabilidade","O fornecedor do controle","O auditor externo"],why:"A aceitação pertence ao responsável de negócio autorizado, não à equipe técnica ou ao auditor."},
  {topic:"Ética profissional",ask:"Ao descobrir uma prática que ameaça o público, qual princípio deve prevalecer?",correct:"Proteger a sociedade, o bem comum e a confiança pública",wrong:["Evitar qualquer impacto na reputação do empregador","Manter silêncio até receber ordem judicial","Priorizar exclusivamente o contrato comercial"],why:"A proteção da sociedade e do bem comum ocupa posição central na ética profissional da ISC2."},
  {topic:"Continuidade de negócios",ask:"Qual resultado é mais importante em uma análise de impacto no negócio?",correct:"Prioridades de recuperação e impactos associados à indisponibilidade",wrong:["Lista completa de vulnerabilidades técnicas","Inventário de licenças de software","Diagrama físico de todos os racks"],why:"A BIA determina impactos, dependências e prioridades que orientam estratégias de continuidade."},
  {topic:"Compliance",ask:"Como tratar um conflito entre política interna e obrigação legal aplicável?",correct:"Atender à obrigação legal e ajustar formalmente a política",wrong:["Seguir a política por ser mais antiga","Ignorar ambas até a próxima auditoria","Permitir que cada departamento escolha"],why:"Requisitos legais aplicáveis prevalecem e a governança deve atualizar os documentos internos."},
 ]},
 {name:"2. Asset Security",concepts:[
  {topic:"Classificação da informação",ask:"Quem é o PRINCIPAL responsável por definir a classificação de um ativo de informação?",correct:"O proprietário da informação",wrong:["O administrador do banco de dados","O operador do service desk","O custodiante de backup"],why:"O proprietário determina valor e classificação; custodiantes implementam os controles definidos."},
  {topic:"Minimização de dados",ask:"Qual prática reduz melhor o risco de privacidade desde a coleta?",correct:"Coletar apenas os dados necessários para a finalidade declarada",wrong:["Criptografar todos os dados e armazená-los indefinidamente","Coletar dados adicionais para possível uso futuro","Compartilhar os dados com todos os departamentos"],why:"Minimização reduz exposição e limita o tratamento ao necessário."},
  {topic:"Retenção",ask:"Como deve ser definido um período de retenção de dados?",correct:"Por requisitos legais, regulatórios e necessidades legítimas do negócio",wrong:["Pelo espaço disponível em disco","Pela preferência do administrador","Sempre pelo maior período tecnicamente possível"],why:"Retenção deve ser justificável e equilibrar obrigações e risco."},
  {topic:"Descarte seguro",ask:"Qual abordagem é mais adequada para mídia que armazenou dados altamente sensíveis?",correct:"Sanitização ou destruição conforme o risco e a possibilidade de reutilização",wrong:["Excluir os arquivos pelo sistema operacional","Formatar rapidamente a unidade","Remover a etiqueta de patrimônio"],why:"Exclusão lógica simples não impede recuperação; o método deve seguir sensibilidade e destino da mídia."},
  {topic:"Privacidade",ask:"Qual medida demonstra melhor limitação de finalidade?",correct:"Usar dados pessoais somente para os propósitos informados e autorizados",wrong:["Disponibilizar os dados para qualquer análise interna","Substituir o aviso de privacidade por um contrato genérico","Manter dados sem prazo definido"],why:"Limitação de finalidade restringe o uso ao contexto comunicado e legítimo."},
 ]},
 {name:"3. Security Architecture and Engineering",concepts:[
  {topic:"Defesa em profundidade",ask:"Qual arquitetura oferece a MAIOR resiliência contra falha de um único controle?",correct:"Camadas independentes e complementares de controles",wrong:["Um único appliance de alta capacidade","Controles duplicados com a mesma falha comum","Confiança irrestrita na rede interna"],why:"Camadas diversas reduzem a probabilidade de uma única falha comprometer todo o sistema."},
  {topic:"Criptografia",ask:"Qual mecanismo oferece confidencialidade para grande volume de dados com melhor desempenho?",correct:"Criptografia simétrica com chave protegida",wrong:["Hash sem chave","Assinatura digital isolada","Codificação Base64"],why:"Algoritmos simétricos são eficientes para dados em massa; hash e assinatura não fornecem confidencialidade."},
  {topic:"Modelagem de ameaças",ask:"Quando a modelagem de ameaças gera maior benefício?",correct:"Durante o projeto, antes de decisões arquiteturais se tornarem caras",wrong:["Somente após um incidente grave","Apenas na desativação do sistema","Depois da auditoria final de produção"],why:"Identificar ameaças cedo permite requisitos e mitigação por design."},
  {topic:"Segurança física",ask:"Qual controle reduz melhor o risco de entrada por tailgating em área restrita?",correct:"Eclusa de segurança com autenticação individual",wrong:["Câmera sem monitoramento","Aviso de área restrita","Iluminação externa adicional"],why:"Uma eclusa controla passagem individual e impede que outra pessoa acompanhe o usuário autorizado."},
  {topic:"Cloud",ask:"No modelo de responsabilidade compartilhada, qual princípio é mais importante?",correct:"Definir claramente controles do provedor e responsabilidades do cliente",wrong:["Assumir que o provedor responde por todos os dados","Replicar controles locais sem análise","Eliminar avaliações de fornecedores"],why:"Responsabilidades variam por serviço e devem ser explicitamente compreendidas e verificadas."},
 ]},
 {name:"4. Communication and Network Security",concepts:[
  {topic:"Segmentação",ask:"Qual medida limita melhor o movimento lateral após comprometimento de uma estação?",correct:"Segmentação com políticas de acesso entre zonas",wrong:["Aumentar a largura de banda do backbone","Usar um único segmento para simplificar operações","Ocultar os nomes dos servidores"],why:"Segmentação e filtragem entre zonas reduzem alcance e propagação."},
  {topic:"VPN",ask:"Qual propriedade é essencial para proteger dados em uma VPN sobre rede não confiável?",correct:"Criptografia e integridade do túnel autenticado",wrong:["Compressão máxima dos pacotes","Endereçamento IP público fixo","Desativação de logs"],why:"Um túnel seguro deve autenticar pares e proteger confidencialidade e integridade."},
  {topic:"Protocolos seguros",ask:"Qual substituição reduz melhor o risco de administração remota em texto claro?",correct:"Usar SSH no lugar de Telnet",wrong:["Usar FTP no lugar de SFTP","Usar HTTP no lugar de HTTPS","Usar SNMPv1 com community padrão"],why:"SSH protege autenticação e sessão administrativa; Telnet transmite dados em texto claro."},
  {topic:"Zero Trust",ask:"Qual decisão está mais alinhada ao Zero Trust?",correct:"Verificar explicitamente cada acesso com contexto e menor privilégio",wrong:["Confiar automaticamente em dispositivos internos","Liberar acesso permanente após o primeiro login","Eliminar segmentação para melhorar experiência"],why:"Zero Trust não presume confiança por localização e reavalia identidade, dispositivo e contexto."},
  {topic:"Wireless",ask:"Qual configuração é preferível para uma nova rede sem fio corporativa?",correct:"WPA3-Enterprise com autenticação individual",wrong:["WEP com chave longa","WPA pessoal compartilhado por toda a empresa","SSID oculto sem criptografia"],why:"WPA3-Enterprise oferece autenticação individual e proteção moderna; chaves compartilhadas ampliam exposição."},
 ]},
 {name:"5. Identity and Access Management (IAM)",concepts:[
  {topic:"Menor privilégio",ask:"Qual ação implementa melhor o princípio do menor privilégio?",correct:"Conceder somente permissões necessárias e revisá-las periodicamente",wrong:["Dar acesso administrativo para evitar chamados","Copiar privilégios do gestor para novos usuários","Manter acessos antigos por conveniência"],why:"Privilégios devem ser mínimos, justificados e removidos quando deixam de ser necessários."},
  {topic:"MFA",ask:"Qual combinação representa fatores de autenticação diferentes?",correct:"Senha e token físico",wrong:["Senha e PIN","Impressão digital e reconhecimento facial","Token físico e aplicativo no mesmo telefone"],why:"Senha é algo que se sabe e token físico é algo que se possui."},
  {topic:"Federação",ask:"Qual é o principal benefício da federação de identidades?",correct:"Permitir confiança controlada entre domínios sem replicar credenciais",wrong:["Eliminar a necessidade de autorização","Garantir acesso anônimo a parceiros","Substituir todas as políticas locais"],why:"Federação troca asserções confiáveis mantendo domínios e responsabilidades distintos."},
  {topic:"Ciclo de vida",ask:"Qual controle reduz melhor o risco quando um funcionário deixa a organização?",correct:"Processo integrado que revoga acessos imediatamente conforme o desligamento",wrong:["Aguardar a revisão trimestral","Trocar apenas a senha do e-mail","Solicitar que o ex-funcionário exclua suas contas"],why:"Desprovisionamento tempestivo e coordenado evita uso indevido de contas órfãs."},
  {topic:"Segregação de funções",ask:"Qual desenho reduz melhor o risco de fraude em pagamentos?",correct:"Separar criação, aprovação e liberação entre pessoas diferentes",wrong:["Concentrar todas as etapas no funcionário mais experiente","Registrar operações sem exigir aprovação","Compartilhar uma conta administrativa"],why:"Separar funções incompatíveis dificulta fraude unilateral e melhora rastreabilidade."},
 ]},
 {name:"6. Security Assessment and Testing",concepts:[
  {topic:"Auditoria",ask:"Qual característica preserva melhor a independência de uma auditoria?",correct:"Auditores sem responsabilidade operacional sobre o objeto avaliado",wrong:["Equipe auditada define as conclusões","Gestor do controle remove achados","Auditor implementa e aprova o próprio controle"],why:"Independência reduz conflito de interesse e aumenta credibilidade das conclusões."},
  {topic:"Teste de intrusão",ask:"O que deve existir ANTES de iniciar um teste de intrusão?",correct:"Escopo, autorização formal e regras de engajamento",wrong:["Publicação dos achados","Exploração irrestrita de terceiros","Desativação permanente dos controles"],why:"Autorização e limites protegem participantes, ativos e continuidade do negócio."},
  {topic:"Vulnerabilidades",ask:"Como priorizar correções de vulnerabilidades de forma mais eficaz?",correct:"Combinar criticidade técnica, exposição, ameaça e impacto no negócio",wrong:["Ordenar apenas pelo identificador CVE","Corrigir somente as mais recentes","Usar exclusivamente a pontuação base"],why:"Risco real depende do contexto, não apenas da severidade técnica."},
  {topic:"Métricas",ask:"Qual métrica é mais útil para a gestão de vulnerabilidades?",correct:"Tempo de correção por criticidade comparado ao prazo definido",wrong:["Número total de e-mails enviados","Quantidade de páginas do relatório","Volume de tráfego da rede"],why:"A métrica liga desempenho operacional ao risco e aos níveis de serviço estabelecidos."},
  {topic:"Testes de controle",ask:"Qual evidência demonstra melhor que um controle opera continuamente?",correct:"Amostras de execução ao longo do período e registros verificáveis",wrong:["Declaração verbal do responsável","Documento de projeto sem evidência operacional","Captura de tela produzida uma única vez"],why:"Efetividade operacional requer evidência representativa durante o período avaliado."},
 ]},
 {name:"7. Security Operations",concepts:[
  {topic:"Resposta a incidentes",ask:"Após confirmar um incidente ativo, qual prioridade orienta a contenção?",correct:"Limitar o impacto preservando evidências e operações críticas",wrong:["Apagar imediatamente todos os sistemas afetados","Divulgar detalhes antes da análise","Ignorar procedimentos para ganhar velocidade"],why:"Contenção deve equilibrar redução de dano, continuidade e preservação forense."},
  {topic:"Logs e SIEM",ask:"Qual prática aumenta mais o valor investigativo de logs distribuídos?",correct:"Sincronização de tempo, centralização e proteção contra alteração",wrong:["Manter somente logs locais sem relógio comum","Excluir eventos bem-sucedidos","Permitir alteração pelos administradores auditados"],why:"Tempo consistente, correlação e integridade são essenciais para reconstruir eventos."},
  {topic:"Disaster Recovery",ask:"O que representa o RTO de um serviço?",correct:"Tempo máximo aceitável para restaurar o serviço",wrong:["Quantidade máxima de dados que pode ser perdida","Tempo entre dois backups","Vida útil do equipamento"],why:"RTO define prazo de recuperação; RPO trata a perda aceitável de dados."},
  {topic:"Forense",ask:"Qual ação preserva melhor a admissibilidade de uma evidência digital?",correct:"Documentar coleta, transferências e integridade na cadeia de custódia",wrong:["Analisar diretamente o original sem registro","Compartilhar a mídia entre equipes sem controle","Alterar timestamps para facilitar a leitura"],why:"Cadeia de custódia e verificação de integridade demonstram controle contínuo da evidência."},
  {topic:"Gestão de mudanças",ask:"Qual controle reduz melhor incidentes causados por mudanças em produção?",correct:"Avaliação, aprovação, teste e plano de reversão proporcionais ao risco",wrong:["Permitir mudanças urgentes sem registro","Testar somente após a implantação","Eliminar segregação para acelerar entregas"],why:"Mudanças controladas são avaliadas, testadas, autorizadas e reversíveis."},
 ]},
 {name:"8. Software Development Security",concepts:[
  {topic:"Secure SDLC",ask:"Quando requisitos de segurança devem ser definidos?",correct:"No início do ciclo e refinados durante todo o desenvolvimento",wrong:["Somente após o lançamento","Apenas no teste de aceitação","Quando ocorrer o primeiro incidente"],why:"Segurança antecipada reduz retrabalho e orienta arquitetura, implementação e testes."},
  {topic:"DevSecOps",ask:"Qual prática integra melhor segurança a um pipeline de entrega?",correct:"Testes automatizados, critérios de bloqueio e correção com responsáveis definidos",wrong:["Uma auditoria manual anual isolada","Remover verificações para aumentar velocidade","Deixar toda segurança para a equipe de operações"],why:"Automação e feedback rápido tornam segurança parte contínua do fluxo de entrega."},
  {topic:"OWASP",ask:"Qual medida reduz melhor o risco de injeção em consultas a banco de dados?",correct:"Consultas parametrizadas e validação adequada de entrada",wrong:["Ocultar mensagens de erro apenas","Aumentar o tamanho máximo dos campos","Codificar a resposta em Base64"],why:"Parametrização separa dados de comandos e é o controle central contra injeção."},
  {topic:"Dependências",ask:"Como gerenciar melhor o risco de componentes de terceiros?",correct:"Inventariar dependências, monitorar vulnerabilidades e atualizar de forma controlada",wrong:["Confiar em qualquer pacote popular","Desativar o registro de versões","Atualizar diretamente em produção sem testes"],why:"Visibilidade, monitoramento e atualização governada reduzem exposição da cadeia de software."},
  {topic:"Revisão de código",ask:"Qual é o maior benefício de revisão de código focada em segurança?",correct:"Encontrar falhas de lógica e implementação antes da produção",wrong:["Garantir ausência total de vulnerabilidades","Substituir todos os testes dinâmicos","Eliminar a necessidade de modelagem de ameaças"],why:"Revisão identifica classes importantes de defeitos, mas complementa outras práticas."},
 ]},
];

export const cisspQuestions:CisspQuestion[]=domains.flatMap((domain,di)=>contexts.flatMap((context,ci)=>domain.concepts.map((c,ki)=>({
 id:`cissp-d${di+1}-${String(ci*5+ki+1).padStart(3,"0")}`,
 statement:`${context} ${c.ask}`,
 options:[c.correct,...c.wrong],answer:0,subject:domain.name,topic:c.topic,
 difficulty:(ci<2?"Médio":"Difícil") as "Médio"|"Difícil",explanation:c.why,certification:"CISSP",examVersion:"2024",
}))));
