import type {CisspQuestion} from "./cissp-bank";
type C={topic:string;ask:string;correct:string;wrong:[string,string,string];why:string};
const contexts=["Uma organização europeia revisa seu programa de privacidade.","Durante uma avaliação do DPO, surge o seguinte cenário.","Uma empresa que trata dados pessoais precisa tomar uma decisão.","Após uma auditoria de proteção de dados, a direção solicita orientação.","Em um projeto internacional, a equipe identifica uma questão de conformidade."];
const areas:{name:string;concepts:C[]}[]=[
 {name:"1. Fundamentos de privacidade e GDPR",concepts:[
  {topic:"Dado pessoal",ask:"Qual informação deve ser tratada como dado pessoal?",correct:"Um identificador online que pode ser relacionado a uma pessoa",wrong:["Um relatório estatístico irreversivelmente anonimizado","Dados de uma empresa sem vínculo com pessoas","Informação pública sobre clima"],why:"Dado pessoal inclui qualquer informação relativa a pessoa identificada ou identificável."},
  {topic:"Dados sensíveis",ask:"Qual exemplo pertence a categoria especial de dados?",correct:"Informação sobre saúde de uma pessoa",wrong:["CEP comercial de uma empresa","Número de patrimônio de um notebook","Preço de um produto"],why:"Dados de saúde integram categorias especiais e exigem condição específica de tratamento."},
  {topic:"Escopo territorial",ask:"Quando o GDPR pode alcançar uma empresa fora da União Europeia?",correct:"Quando oferece bens ou monitora pessoas localizadas na União Europeia",wrong:["Somente quando possui sede física em Bruxelas","Apenas quando recebe pagamento em euro","Nunca, por estar fora da União Europeia"],why:"O alcance extraterritorial considera oferta de bens/serviços e monitoramento de pessoas na UE."},
  {topic:"Accountability",ask:"Qual evidência demonstra melhor responsabilização?",correct:"Decisões documentadas, controles operantes e revisões verificáveis",wrong:["Uma política sem registros de execução","Declaração verbal de conformidade","Contrato genérico sem responsáveis"],why:"Accountability exige cumprir e também demonstrar a conformidade."},
 ]},
 {name:"2. Princípios e bases legais",concepts:[
  {topic:"Limitação de finalidade",ask:"Qual ação está mais alinhada à limitação de finalidade?",correct:"Usar dados somente para objetivos específicos informados e compatíveis",wrong:["Reutilizar dados para qualquer objetivo futuro","Omitir a finalidade para manter flexibilidade","Compartilhar com todos os parceiros"],why:"Finalidades devem ser específicas, explícitas e legítimas; novos usos precisam de análise de compatibilidade."},
  {topic:"Minimização",ask:"Qual escolha aplica melhor a minimização de dados?",correct:"Coletar apenas atributos necessários para executar o serviço",wrong:["Coletar tudo porque o armazenamento é barato","Manter campos opcionais ocultos do titular","Usar consentimento para justificar qualquer coleta"],why:"Os dados devem ser adequados, relevantes e limitados ao necessário."},
  {topic:"Base legal",ask:"Antes de iniciar um tratamento, qual decisão é essencial?",correct:"Identificar e documentar uma base legal aplicável à finalidade",wrong:["Escolher consentimento em todos os casos","Aguardar reclamação de um titular","Definir a base legal após a coleta"],why:"A licitude deve ser estabelecida antes do tratamento e vinculada à finalidade concreta."},
  {topic:"Consentimento",ask:"Qual característica torna o consentimento válido?",correct:"Ser livre, específico, informado e inequívoco, com retirada facilitada",wrong:["Ser incluído em termos obrigatórios e genéricos","Usar caixas previamente marcadas","Impedir retirada após a primeira utilização"],why:"Consentimento exige escolha real, transparência e possibilidade de retirada tão fácil quanto conceder."},
 ]},
 {name:"3. Direitos dos titulares",concepts:[
  {topic:"Transparência",ask:"Como apresentar informações ao titular de forma adequada?",correct:"Em linguagem clara, acessível e no momento apropriado",wrong:["Apenas em contrato jurídico extenso","Somente quando o titular reclamar","Em documento interno não publicado"],why:"Informação transparente deve ser concisa, inteligível, acessível e clara."},
  {topic:"Acesso",ask:"Ao receber pedido de acesso válido, o que a organização deve fornecer?",correct:"Confirmação do tratamento, cópia dos dados e informações pertinentes",wrong:["Somente a política de privacidade","Credenciais de outros usuários","Código-fonte completo dos sistemas"],why:"O direito de acesso abrange dados pessoais e informações sobre o tratamento, respeitados direitos de terceiros."},
  {topic:"Apagamento",ask:"O pedido de apagamento deve ser sempre atendido?",correct:"Não; deve ser avaliado contra obrigações legais e exceções aplicáveis",wrong:["Sim, sem qualquer exceção","Não, porque dados pertencem ao controlador","Somente mediante ordem policial"],why:"O direito não é absoluto e pode ceder diante de obrigações ou interesses previstos no GDPR."},
  {topic:"Portabilidade",ask:"Qual formato favorece o direito à portabilidade?",correct:"Formato estruturado, de uso corrente e legível por máquina",wrong:["Imagem escaneada sem estrutura","Documento criptografado sem chave","Relatório agregado sem dados do titular"],why:"Portabilidade busca reutilização e transmissão efetiva dos dados fornecidos pelo titular."},
 ]},
 {name:"4. Papéis, governança e DPO",concepts:[
  {topic:"Controlador",ask:"Quem determina as finalidades e os meios essenciais do tratamento?",correct:"O controlador",wrong:["Sempre o operador de datacenter","A autoridade supervisora","O titular dos dados"],why:"O controlador define por que e como o tratamento ocorre."},
  {topic:"Operador",ask:"Qual obrigação é central para um processador?",correct:"Tratar dados conforme instruções documentadas do controlador",wrong:["Definir novas finalidades sem autorização","Responder por todas as decisões do controlador","Usar os dados para marketing próprio"],why:"O processador atua sob instruções, com contrato e deveres próprios de segurança e cooperação."},
  {topic:"Independência do DPO",ask:"Qual arranjo protege melhor a independência do DPO?",correct:"Reporte ao mais alto nível e ausência de instruções sobre suas conclusões",wrong:["Bônus condicionado à ausência de incidentes","Subordinação ao responsável pelo tratamento avaliado","Aprovação prévia de todos os pareceres pelo marketing"],why:"O DPO deve atuar sem instruções quanto às suas tarefas e acessar a alta administração."},
  {topic:"Conflito de interesses",ask:"Qual função tende a conflitar com a atuação do DPO?",correct:"Cargo que determina finalidades e meios do tratamento",wrong:["Consultoria sem poder decisório","Treinamento independente","Monitoramento de conformidade"],why:"Há conflito quando a mesma pessoa decide o tratamento que deveria monitorar com independência."},
 ]},
 {name:"5. Riscos, DPIA e segurança",concepts:[
  {topic:"DPIA",ask:"Quando uma avaliação de impacto é especialmente necessária?",correct:"Antes de tratamento provavelmente capaz de gerar alto risco às pessoas",wrong:["Depois que o sistema for desativado","Apenas quando houver vazamento","Somente para dados em papel"],why:"A DPIA é preventiva e deve anteceder tratamentos de provável alto risco."},
  {topic:"Privacy by design",ask:"Qual prática representa proteção de dados desde a concepção?",correct:"Incorporar requisitos e configurações protetivas desde o projeto",wrong:["Adicionar aviso somente após o lançamento","Coletar o máximo e apagar se houver reclamação","Transferir toda responsabilidade ao usuário"],why:"Privacy by design integra princípios e salvaguardas ao ciclo de vida do tratamento."},
  {topic:"Segurança",ask:"Como escolher medidas técnicas e organizacionais apropriadas?",correct:"Com base no risco, estado da técnica, custos e natureza do tratamento",wrong:["Aplicando a mesma lista a todos os sistemas","Usando apenas criptografia","Seguindo a preferência do fornecedor"],why:"O GDPR exige abordagem proporcional ao risco e ao contexto."},
  {topic:"Pseudonimização",ask:"Dados pseudonimizados deixam de ser dados pessoais?",correct:"Não, se puderem ser relacionados novamente com informação adicional",wrong:["Sim, em todos os casos","Sim, desde que estejam criptografados","Não existem dados pseudonimizados no GDPR"],why:"Pseudonimização reduz risco, mas normalmente mantém os dados no escopo do GDPR."},
 ]},
 {name:"6. Incidentes, transferências e PIMS",concepts:[
  {topic:"Violação de dados",ask:"Qual é a primeira resposta gerencial a uma possível violação?",correct:"Conter, investigar, avaliar risco e documentar a decisão de notificação",wrong:["Notificar publicamente antes de confirmar fatos","Apagar todas as evidências","Aguardar a auditoria anual"],why:"A resposta deve controlar o incidente e sustentar decisão tempestiva e documentada."},
  {topic:"Notificação",ask:"Quando a autoridade supervisora deve ser notificada?",correct:"Quando a violação provavelmente gerar risco aos direitos e liberdades, em regra até 72 horas",wrong:["Somente após 30 dias","Em toda indisponibilidade sem análise","Apenas se o titular autorizar"],why:"O GDPR prevê notificação sem demora indevida e, quando possível, em 72 horas, salvo ausência provável de risco."},
  {topic:"Transferência internacional",ask:"Antes de transferir dados para terceiro país, o que deve ser verificado?",correct:"Mecanismo válido de transferência e proteção efetiva no destino",wrong:["Somente o custo do provedor","A existência de conexão criptografada basta","A nacionalidade do diretor da empresa"],why:"Transferências exigem base do Capítulo V e avaliação das salvaguardas aplicáveis."},
  {topic:"PIMS ISO 27701",ask:"Qual benefício principal de um PIMS alinhado à ISO/IEC 27701?",correct:"Estruturar governança e controles de privacidade de forma auditável",wrong:["Substituir automaticamente todas as leis","Eliminar riscos de privacidade","Dispensar responsabilidades do controlador"],why:"O PIMS organiza responsabilidades, processos e evidências, mas não elimina obrigações legais."},
 ]},
];
export const exinDpoQuestions:CisspQuestion[]=areas.flatMap((a,ai)=>contexts.flatMap((ctx,ci)=>a.concepts.map((c,ki)=>({id:`exin-dpo-a${ai+1}-${String(ci*4+ki+1).padStart(3,"0")}`,statement:`${ctx} ${c.ask}`,options:[c.correct,...c.wrong],answer:0,subject:a.name,topic:c.topic,difficulty:(ci<2?"Médio":"Difícil") as "Médio"|"Difícil",explanation:c.why,certification:"EXIN Data Protection Officer",examVersion:"PDPP 202302"}))));
