"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import {useEffect,useMemo,useState} from "react";
import {cisspQuestions,type CisspQuestion} from "./cissp-bank";

type View="library"|"sessions"|"review"|"history"|"manage";
type Mode="exam"|"study"|"review";
type Attempt={id:string;date:string;mode:Mode;answers:Record<string,number>;score:number;total:number;seconds:number};
type Setup={mode:Mode;count:number;domains:string[];difficulty:string[];shuffle:boolean;shuffleOptions:boolean;minutes:number;feedback:boolean};
const DEFAULT:Setup={mode:"exam",count:20,domains:[],difficulty:["Fácil","Médio","Difícil"],shuffle:true,shuffleOptions:true,minutes:36,feedback:false};
const mix=<T,>(a:T[])=>{const x=[...a];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};

export default function App(){
 const questions=cisspQuestions,[view,setView]=useState<View>("library"),[attempts,setAttempts]=useState<Attempt[]>([]),[marked,setMarked]=useState<string[]>([]),[setup,setSetup]=useState(DEFAULT),[config,setConfig]=useState(false),[session,setSession]=useState<CisspQuestion[]>([]),[at,setAt]=useState(0),[answers,setAnswers]=useState<Record<string,number>>({}),[paused,setPaused]=useState(false),[elapsed,setElapsed]=useState(0),[result,setResult]=useState<Attempt|null>(null),[toast,setToast]=useState("");
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("studysim-v4")||"{}");setAttempts(s.attempts||[]);setMarked(s.marked||[])}catch{}if("serviceWorker" in navigator)navigator.serviceWorker.register(`${location.pathname.startsWith("/exame")?"/exame":""}/sw.js`)},[]);
 useEffect(()=>localStorage.setItem("studysim-v4",JSON.stringify({attempts,marked})),[attempts,marked]);
 useEffect(()=>{if(!session.length||paused)return;const t=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(t)},[session,paused]);
 const domains=useMemo(()=>[...new Set(questions.map(q=>q.subject))],[questions]);
 const last=attempts.at(-1),allAnswers=attempts.flatMap(a=>Object.entries(a.answers)),accuracy=allAnswers.length?Math.round(attempts.reduce((n,a)=>n+a.score,0)/allAnswers.length*100):0;
 const wrong=new Set(attempts.flatMap(a=>Object.entries(a.answers).filter(([id,v])=>questions.find(q=>q.id===id)?.answer!==v).map(([id])=>id)));
 const note=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2000)};
 function begin(custom:Partial<Setup>={}){const s={...setup,...custom};let pool=questions.filter(q=>(!s.domains.length||s.domains.includes(q.subject))&&s.difficulty.includes(q.difficulty));if(s.mode==="review")pool=pool.filter(q=>wrong.has(q.id)||marked.includes(q.id));if(s.shuffle)pool=mix(pool);pool=pool.slice(0,Math.min(s.count,pool.length)).map(q=>{if(!s.shuffleOptions)return q;const x=mix(q.options.map((text,index)=>({text,index})));return{...q,options:x.map(v=>v.text),answer:x.findIndex(v=>v.index===q.answer)}});if(!pool.length){note("Nenhuma questão disponível para esse modo");return}setSetup(s);setSession(pool);setAnswers({});setAt(0);setElapsed(0);setPaused(false);setConfig(false)}
 function finish(){const score=session.filter(q=>answers[q.id]===q.answer).length;const a:Attempt={id:crypto.randomUUID(),date:new Date().toISOString(),mode:setup.mode,answers:{...answers},score,total:session.length,seconds:elapsed};setAttempts(x=>[...x,a]);setResult(a);setSession([])}
 if(session.length)return <Player questions={session} at={at} setAt={setAt} answers={answers} setAnswers={setAnswers} marked={marked} setMarked={setMarked} setup={setup} paused={paused} setPaused={setPaused} elapsed={elapsed} exit={()=>setSession([])} finish={finish}/>;
 return <div className="shell"><aside className="side"><div className="side-brand"><b>S</b><span>StudySim<small>Exam Player</small></span></div><nav>{(["library","sessions","review","history","manage"] as View[]).map((v,i)=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}><i>{["▦","▶","↻","◷","⚙"][i]}</i>{["Biblioteca","Simulados","Revisão","Histórico","Gerenciar"][i]}</button>)}</nav><div className="side-foot"><span>RC</span><div><b>Rodolfo Costa</b><small>Dados locais</small></div></div></aside><main className="workspace"><header className="workspace-head"><div><small>ISC2 LEARNING</small><h1>{({library:"Biblioteca de provas",sessions:"Criar simulado",review:"Revisão inteligente",history:"Histórico e desempenho",manage:"Gerenciar conteúdo"} as Record<View,string>)[view]}</h1></div><button className="icon-btn" onClick={()=>note("Tudo sincronizado neste dispositivo")}>♢</button></header><section className="workspace-body">
 {view==="library"&&<Library count={questions.length} accuracy={accuracy} attempts={attempts.length} last={last} quick={()=>begin({mode:"study",count:10,minutes:0,feedback:true})} full={()=>begin({mode:"exam",count:100,minutes:180,feedback:false})} configure={()=>setConfig(true)}/>}
 {view==="sessions"&&<SessionHub start={begin} advanced={()=>setConfig(true)} wrong={wrong.size} marked={marked.length}/>}
 {view==="review"&&<Review wrong={wrong.size} marked={marked.length} start={()=>begin({mode:"review",count:50,minutes:0,feedback:true})}/>}
 {view==="history"&&<History attempts={attempts}/>}
 {view==="manage"&&<Manage count={questions.length} exportData={()=>{const b=new Blob([JSON.stringify({questions,attempts,marked},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="cissp-study.exam.json";a.click()}}/>}
 </section></main>{config&&<Config setup={setup} setSetup={setSetup} domains={domains} close={()=>setConfig(false)} start={()=>begin()}/>} {result&&<Report attempt={result} questions={questions} close={()=>{setResult(null);setView("history")}}/>}{toast&&<div className="toast">{toast}</div>}<MobileNav view={view} setView={setView}/></div>
}

function Library({count,accuracy,attempts,last,quick,full,configure}:{count:number;accuracy:number;attempts:number;last?:Attempt;quick:()=>void;full:()=>void;configure:()=>void}){return <><div className="welcome"><div><span>MINHAS PROVAS</span><h2>Escolha uma prova e comece em poucos cliques.</h2><p>Seu progresso e sessões ficam disponíveis neste dispositivo.</p></div><div className="welcome-stat"><b>{accuracy}%</b><small>média geral</small></div></div><article className="exam-card"><div className="exam-logo">C</div><div className="exam-info"><div className="eyebrow">ISC2 · EXAM OUTLINE 2024 · PT-BR</div><h2>CISSP</h2><p>Certified Information Systems Security Professional</p><div className="exam-meta"><span><b>{count}</b> questões</span><span><b>8</b> domínios</span><span><b>{attempts}</b> sessões</span><span><b>Offline</b> disponível</span></div><div className="progress-line"><i style={{width:`${Math.min(100,attempts*4)}%`}}/></div><small>{last?`Último acesso: ${new Date(last.date).toLocaleDateString("pt-BR")}`:"Você ainda não iniciou uma sessão"}</small></div><div className="exam-actions"><button className="primary" onClick={last?quick:quick}>▶ {last?"Continuar estudando":"Simulado rápido"}</button><button onClick={full}>Prova completa</button><button onClick={configure}>Configurar</button></div></article><div className="domain-strip">{["D1 Riscos","D2 Ativos","D3 Arquitetura","D4 Redes","D5 IAM","D6 Testes","D7 Operações","D8 Software"].map(x=><span key={x}>{x}</span>)}</div></>}
function SessionHub({start,advanced,wrong,marked}:{start:(x:Partial<Setup>)=>void;advanced:()=>void;wrong:number;marked:number}){const cards=[{t:"Simulado rápido",d:"10 questões · modo estudo",i:"⚡",x:{mode:"study" as Mode,count:10,minutes:0,feedback:true}},{t:"Prova completa",d:"100 questões · 180 minutos",i:"✓",x:{mode:"exam" as Mode,count:100,minutes:180,feedback:false}},{t:"Somente erros",d:`${wrong} questões disponíveis`,i:"↻",x:{mode:"review" as Mode,count:wrong,minutes:0,feedback:true}},{t:"Questões marcadas",d:`${marked} questões salvas`,i:"★",x:{mode:"review" as Mode,count:marked,minutes:0,feedback:true}}];return <><div className="mode-grid">{cards.map(c=><button key={c.t} onClick={()=>start(c.x)}><i>{c.i}</i><b>{c.t}</b><small>{c.d}</small><span>Começar →</span></button>)}</div><button className="advanced" onClick={advanced}>⚙ Configurações avançadas e filtros</button></>}
function Review({wrong,marked,start}:{wrong:number;marked:number;start:()=>void}){return <div className="review-panel"><span>REVISÃO INTELIGENTE</span><h2>Concentre-se onde existe maior oportunidade.</h2><p>O StudySim reúne erros e marcações das suas sessões reais. O banco nunca inventa progresso.</p><div><article><b>{wrong}</b><span>Questões erradas</span></article><article><b>{marked}</b><span>Marcadas para revisar</span></article></div><button className="primary" onClick={start}>Iniciar revisão</button></div>}
function History({attempts}:{attempts:Attempt[]}){if(!attempts.length)return <div className="empty"><b>◷</b><h2>Nenhuma sessão concluída</h2><p>Seus relatórios aparecerão aqui após o primeiro simulado.</p></div>;return <div className="history-list">{[...attempts].reverse().map(a=><article key={a.id}><span className="score">{Math.round(a.score/a.total*100)}%</span><div><b>{a.mode==="exam"?"Modo prova":a.mode==="study"?"Modo estudo":"Revisão"}</b><small>{new Date(a.date).toLocaleString("pt-BR")} · {a.total} questões · {Math.round(a.seconds/60)} min</small></div><em>{a.score}/{a.total}</em></article>)}</div>}
function Manage({count,exportData}:{count:number;exportData:()=>void}){return <div className="manage-grid"><article><i>▤</i><h3>Banco CISSP</h3><p>{count} questões autorais, oito domínios, versão 2024.</p><button onClick={exportData}>Exportar .exam.json</button></article><article><i>⇧</i><h3>Importador</h3><p>Importação JSON estruturada com validação antes da publicação.</p><button disabled>Em preparação</button></article><article><i>✎</i><h3>Editor de questões</h3><p>Fluxo separado do player para manter a prova limpa.</p><button disabled>Em preparação</button></article></div>}

function Player({questions,at,setAt,answers,setAnswers,marked,setMarked,setup,paused,setPaused,elapsed,exit,finish}:{questions:CisspQuestion[];at:number;setAt:(n:number)=>void;answers:Record<string,number>;setAnswers:(x:Record<string,number>)=>void;marked:string[];setMarked:(x:string[])=>void;setup:Setup;paused:boolean;setPaused:(x:boolean)=>void;elapsed:number;exit:()=>void;finish:()=>void}){const q=questions[at],selected=answers[q.id];return <main className="player"><header><button onClick={exit}>×</button><div><small>CISSP · {setup.mode==="exam"?"Modo prova":setup.mode==="study"?"Modo estudo":"Revisão"}</small><b>Questão {at+1} de {questions.length}</b></div><div className="player-time">◷ {String(Math.floor(elapsed/60)).padStart(2,"0")}:{String(elapsed%60).padStart(2,"0")} <button onClick={()=>setPaused(!paused)}>{paused?"Retomar":"Pausar"}</button></div></header><div className="player-layout"><aside><h3>Questões</h3><div className="question-map">{questions.map((x,i)=><button key={x.id} className={`${i===at?"current":""} ${answers[x.id]!==undefined?"answered":""} ${marked.includes(x.id)?"marked":""}`} onClick={()=>setAt(i)}>{i+1}</button>)}</div><div className="legend"><span>● Respondida</span><span>★ Marcada</span><span>○ Não respondida</span></div></aside><section className="player-question"><div className="question-tags"><span>{q.subject}</span><span>{q.topic}</span><span>{q.difficulty}</span></div><h1>{q.statement}</h1><div className="player-options">{q.options.map((o,i)=><button key={i} className={selected===i?"selected":""} onClick={()=>setAnswers({...answers,[q.id]:i})}><b>{String.fromCharCode(65+i)}</b><span>{o}</span></button>)}</div>{setup.feedback&&selected!==undefined&&<div className={`feedback ${selected===q.answer?"ok":"bad"}`}><b>{selected===q.answer?"✓ Resposta correta":"× Resposta incorreta"}</b><p>{q.explanation}</p></div>}<footer><button disabled={!at} onClick={()=>setAt(at-1)}>← Anterior</button><button onClick={()=>setMarked(marked.includes(q.id)?marked.filter(x=>x!==q.id):[...marked,q.id])}>{marked.includes(q.id)?"★ Marcada":"☆ Marcar"}</button><span>{Object.keys(answers).length}/{questions.length} respondidas</span><button className="primary" onClick={()=>at<questions.length-1?setAt(at+1):finish()}>{at<questions.length-1?"Próxima →":"Finalizar"}</button></footer></section></div>{paused&&<div className="pause"><b>Simulado pausado</b><button className="primary" onClick={()=>setPaused(false)}>Retomar</button></div>}</main>}
function Config({setup,setSetup,domains,close,start}:{setup:Setup;setSetup:(x:Setup)=>void;domains:string[];close:()=>void;start:()=>void}){const p=(x:Partial<Setup>)=>setSetup({...setup,...x});return <div className="overlay"><div className="modal config-modal"><div className="modal-head"><div><small>CONFIGURAÇÃO AVANÇADA</small><h2>Criar simulado</h2></div><button onClick={close}>×</button></div><div className="config-scroll"><fieldset><legend>Tipo de sessão</legend>{([['exam','Modo prova'],['study','Modo estudo'],['review','Revisão inteligente']] as [Mode,string][]).map(x=><label className="check" key={x[0]}><input type="radio" checked={setup.mode===x[0]} onChange={()=>p({mode:x[0],feedback:x[0]!=="exam"})}/>{x[1]}</label>)}</fieldset><fieldset><legend>Quantidade</legend><div className="amounts">{[10,20,50,100].map(n=><button className={setup.count===n?"active":""} onClick={()=>p({count:n})} key={n}>{n}</button>)}<input type="number" min="1" max="200" value={setup.count} onChange={e=>p({count:+e.target.value})}/></div></fieldset><fieldset><legend>Domínios</legend>{domains.map(d=><label className="check" key={d}><input type="checkbox" checked={setup.domains.includes(d)} onChange={e=>p({domains:e.target.checked?[...setup.domains,d]:setup.domains.filter(x=>x!==d)})}/>{d}</label>)}</fieldset><fieldset><legend>Opções</legend><label className="check"><input type="checkbox" checked={setup.shuffle} onChange={e=>p({shuffle:e.target.checked})}/>Embaralhar questões</label><label className="check"><input type="checkbox" checked={setup.shuffleOptions} onChange={e=>p({shuffleOptions:e.target.checked})}/>Embaralhar alternativas</label><label className="check"><input type="checkbox" checked={setup.feedback} onChange={e=>p({feedback:e.target.checked})}/>Feedback após cada questão</label><label>Tempo em minutos<input type="number" min="0" value={setup.minutes} onChange={e=>p({minutes:+e.target.value})}/></label></fieldset></div><div className="modal-actions"><button onClick={close}>Cancelar</button><button className="primary" onClick={start}>Iniciar simulado</button></div></div></div>}
function Report({attempt,questions,close}:{attempt:Attempt;questions:CisspQuestion[];close:()=>void}){const rows=[...new Set(questions.map(q=>q.subject))].map(d=>{const qs=questions.filter(q=>q.subject===d&&attempt.answers[q.id]!==undefined);return[d,qs.length?Math.round(qs.filter(q=>attempt.answers[q.id]===q.answer).length/qs.length*100):0] as const}).filter(x=>x[1]||Object.keys(attempt.answers).some(id=>questions.find(q=>q.id===id)?.subject===x[0]));return <div className="overlay"><div className="modal report"><span>RESULTADO DO SIMULADO</span><h2>{Math.round(attempt.score/attempt.total*100)}%</h2><p>{attempt.score} acertos de {attempt.total} · {Math.round(attempt.seconds/60)} minutos</p><div>{rows.map(r=><label key={r[0]}><span>{r[0]}</span><i><b style={{width:`${r[1]}%`}}/></i><em>{r[1]}%</em></label>)}</div><button className="primary wide" onClick={close}>Ver histórico</button></div></div>}
function MobileNav({view,setView}:{view:View;setView:(v:View)=>void}){return <nav className="mobile-nav">{(["library","sessions","review","history","manage"] as View[]).map((v,i)=><button className={view===v?"active":""} onClick={()=>setView(v)} key={v}><i>{["▦","▶","↻","◷","⚙"][i]}</i><small>{["Provas","Simular","Revisar","Histórico","Gestão"][i]}</small></button>)}</nav>}
