name: Publicar VinoViva

on:
  push:
    branches: ["vinoviva-hosting"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-vinoviva"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Baixar projeto
        uses: actions/checkout@v6
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - name: Enviar arquivos estáticos
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."
      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
